# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c5b61a85ce3c6ac2c74494ac36dbbac4343d5314eefef72a29c79b9f5c5c125ec2d8c893e76608a0b45bd6a14b62288d9c59462e40b744bea29d5f39ed9a840

test:
  secret_key_base: 3f0893ec7b44e2a4f15f6a4be4b60e5d0a0fd9e19fe4c5e392b80bb2f3f21a66002a493cc5840913e93b5b767d6655edd7a2b1a1bd4fbb67956db1f7aac13a60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
